blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/thriving-dev/micronaut-gradle-renovate-example-0/discussions
    about: Use discussions if you have another issue, an idea for improvement or for asking questions.
